latexdiff <- function(ref_old, ref_new, rmd, out = "diff.tex", clean = TRUE) {
    tex <- rmd
    no_ext <- tools::file_path_sans_ext(tex)
    if (tools::file_ext(tex) != "tex") tex <- paste0(no_ext, ".tex")

    if (!file.exists(tex)) {
        stop(sprintf("Failed to find LaTeX input '%s'.", normalizePath(tex, mustWork = FALSE)))
    }

    if (Sys.which("latexdiff-vc") == "") {
        message(
            "Failed to find 'latexdiff-vc'. ",
            "Trying to install using 'tinytex::tlmgr_install(\"latexdiff\")"
        )
        tinytex::tlmgr_install("latexdiff")
    }

    processx::run(
        "latexdiff-vc",
        c(
            "--git", "--force",
            "-r", ref_old, "-r", ref_new,
            tex
        )
    )

    # remove temporary files generated by latexdiff
    if (clean) {
        unlink(list.files(
            dirname(tex),
            sprintf("%s-((old)|(new))tmp-\\d+\\.tex", basename(no_ext)),
            full.names = TRUE
        ))
    }

    diff <- sprintf("%s-diff%s-%s.tex", no_ext, ref_old, ref_new)
    if (!file.exists(diff)) {
        stop("'latexdiff' failed to generate the TeX diff file.")
    }

    out <- file.path(dirname(no_ext), out)
    stopifnot(file.rename(diff, out))
    out
}

render_diff <- function(rmd, diff, ref_old, ref_new) {
    if (fs::is_absolute_path(rmd)) {
        stop("'rmd' should be a relative path.")
    }

    if (fs::is_absolute_path(diff)) {
        stop("'diff' should be a relative path.")
    }

    # make sure rmd and diff are in the same root folder
    if (fs::path_common(c(rmd, diff)) == "") {
        stop("Please make sure 'rmd' and 'diff' share the same root folder.")
    }

    # create a temporary folder to store data
    dir <- tempfile("latexdiff")
    dir.create(dir)

    # copy whole working directory to the temporary folder
    stopifnot(all(
        file.copy(list.files(all.files = TRUE, no.. = TRUE), dir,
            recursive = TRUE, overwrite = TRUE
        )
    ))

    # make sure 'rmd' and 'diff' exists in the Git repo
    if (!file.exists(file.path(dir, rmd))) {
        stop("Failed to locate 'rmd' in the Git working tree.")
    }
    if (!file.exists(file.path(dir, diff))) {
        stop("Failed to locate 'diff' in the Git working tree.")
    }

    # create branches to restore old and new paper data
    if (gert::git_branch_exists("old", repo = dir)) gert::git_branch_delete("old", repo = dir)
    gert::git_branch_create("old", ref_old, checkout = FALSE, repo = dir)
    if (gert::git_branch_exists("new", repo = dir)) gert::git_branch_delete("new", repo = dir)
    gert::git_branch_create("new", ref_new, checkout = FALSE, repo = dir)

    # checkout 'new' and 'old' to extract all file dependencies for both
    # versions
    gert::git_branch_checkout("new", repo = dir, force = TRUE)
    deps_new <- rmd_deps(file.path(dir, rmd))
    gert::git_branch_checkout("old", repo = dir, force = TRUE)
    deps_old <- rmd_deps(file.path(dir, rmd))

    # find missing files in new version
    deps_miss <- setdiff(deps_old, deps_new)

    # copy missing files into another temporary folder while keeping the folder
    # strucuture
    dir_tmp <- tempfile("latexdiff")
    dir.create(dir_tmp)
    file_tmp <- file.path(dir_tmp, fs::path_rel(deps_miss, dir))
    if (any(!dir.exists(dirs_file_tmp <- unique(dirname(file_tmp))))) {
        dir.create(dirs_file_tmp[!dir.exists(dirs_file_tmp)], recursive = TRUE)
    }
    stopifnot(all(file.copy(deps_miss, file_tmp, overwrite = TRUE)))

    # change to newer paper branch and copy missing files back so that it
    # contains all files needed to render the diff version
    gert::git_branch_checkout("new", repo = dir, force = TRUE)
    stopifnot(all(file.copy(file_tmp, deps_miss)))

    new_diff <- file.path(
        # get the directory path where the diff lives in the temporary folder
        fs::path_abs(fs::path_rel(dirname(rmd), diff), file.path(dir, diff)),
        basename(diff)
    )
    stopifnot(file.copy(file.path(dir, diff), new_diff, overwrite = TRUE))
    fs::file_copy(file.path(dir, diff), new_diff, overwrite = TRUE)

    old <- getwd()
    setwd(dirname(new_diff))
    out <- tinytex::latexmk(basename(new_diff), "pdflatex")
    setwd(old)
    on.exit(setwd(old), add = TRUE)

    new_out <- fs::path_rel(file.path(dirname(diff), out))
    stopifnot(file.copy(file.path(dirname(new_diff), out), new_out, overwrite = TRUE))

    unlink(c(dir, dir_tmp), recursive = TRUE)
    new_out
}
